---
# This file contains the handlers for ssh

- name: restart sshd
  service: name=ssh state=restarted
  tags:
    - ssh

- name: save iptables
  shell: "/root/bin/save-iptables < /dev/null"
  tags:
    - ssh
