#!/usr/bin/env python2

import commands
import sys

def print_chain(name):
    output = commands.getoutput('iptables -nvL {0}'.format(name))
    ctr = 0
    for line in output.split('\n'):
        if line.startswith('Chain'):
            print(line)
            print('  # pkts  in prot             src             dst          target options')
        elif line.startswith(' pkts'):
            continue
        else:
            ctr += 1
            t = line.split()
            
            rule = '{0:>3}{1:>6}{2:>4}{3:>5}{4:>16}{5:>16}{6:>16}'.format(ctr, t[0], t[5], t[3], t[7], t[8], t[2])
            if 'ESTABLISHED' in line:
                rule += ' established'
            elif 'INVALID' in line:
                rule += ' invalid'
            elif 'LOG' in line:
                del(t[9:])
            elif 'RETURN' in line:
                continue
            elif len(t) > 9:
                rule += ' '
                rule += ' '.join(t[9:])
            print(rule)
    print('')

if __name__ == '__main__':
    if len(sys.argv) > 1:
        chains = [item.upper() for item in sys.argv[1:]]
    else:
        chains = commands.getoutput("iptables -nL | grep ^Chain | egrep -v 'OUTPUT|FORWARD' | awk '{print $2}'").split()
    [print_chain(name) for name in chains]
