---
# This playbook contains the common tasks which are applied to all nodes in
# the HKJL network.

- name: Configure the base distribution
  hosts: all
  sudo: yes
  roles:
    - inventory
    - base_fhs
    - firewall
    - repositories
    - firmware
    - base_software
