---
# This playbook contains the common tasks which are applied to all nodes in
# the HKJL network.

- name: Configure the base distribution
  hosts: all
  sudo: yes
  sudo_user: root
  roles:
    - inventory
    - base_fhs
    - firewall
    - repositories
    - firmware
    - base_software
    - locales
    - haveged
    - ntp
    - sudo
    - server_hardening
    - server_banners
    - ssl
    - ssh
    - rsyslog
    - snmpd
    - exim
    - user_management
